#!/bin/bash

# Generate env-config.js with runtime environment variables
cat <<EOF > /usr/share/nginx/html/env-config.js
window.__ENV__ = {
  BRANDFETCH_TOKEN: "${BRANDFETCH_TOKEN:-}",
  SNOWHOUSE_AUTH_TOKEN: "${SNOWHOUSE_AUTH_TOKEN:-}",
  API_ENDPOINT_RETAIL: "${API_ENDPOINT_RETAIL:-}",
  API_ENDPOINT_ADS: "${API_ENDPOINT_ADS:-}",
  API_ENDPOINT_FIN_INVESTMENT_PORTFOLIO_ANALYTICS: "${API_ENDPOINT_FIN_INVESTMENT_PORTFOLIO_ANALYTICS:-}",
  API_ENDPOINT_FIN_ASSETS_MANAGEMENT_ADVISOR: "${API_ENDPOINT_FIN_ASSETS_MANAGEMENT_ADVISOR:-}",
  API_ENDPOINT_FIN_CLAIMS_PROCESSOR: "${API_ENDPOINT_FIN_CLAIMS_PROCESSOR:-}",
  API_ENDPOINT_HS_CLINICAL_TRIALS: "${API_ENDPOINT_HS_CLINICAL_TRIALS:-}",
  API_ENDPOINT_HS_GENOMICS: "${API_ENDPOINT_HS_GENOMICS:-}",
  API_ENDPOINT_MAN_PREDICTIVE_MAINTENANCE: "${API_ENDPOINT_MAN_PREDICTIVE_MAINTENANCE:-}",
  API_ENDPOINT_MAN_SUPPLY_CHAIN_ASSISTANT: "${API_ENDPOINT_MAN_SUPPLY_CHAIN_ASSISTANT:-}",
  RETAIL_AUTH_TOKEN: "${RETAIL_AUTH_TOKEN:-}",
  ADS_AUTH_TOKEN: "${ADS_AUTH_TOKEN:-}",
  FIN_INVESTMENT_PORTFOLIO_ANALYTICS_AUTH_TOKEN: "${FIN_INVESTMENT_PORTFOLIO_ANALYTICS_AUTH_TOKEN:-}",
  FIN_ASSETS_MANAGEMENT_ADVISOR_AUTH_TOKEN: "${FIN_ASSETS_MANAGEMENT_ADVISOR_AUTH_TOKEN:-}",
  FIN_CLAIMS_PROCESSOR_AUTH_TOKEN: "${FIN_CLAIMS_PROCESSOR_AUTH_TOKEN:-}",
  HS_CLINICAL_TRIALS_AUTH_TOKEN: "${HS_CLINICAL_TRIALS_AUTH_TOKEN:-}",
  HS_GENOMICS_AUTH_TOKEN: "${HS_GENOMICS_AUTH_TOKEN:-}",
  MAN_PREDICTIVE_MAINTENANCE_AUTH_TOKEN: "${MAN_PREDICTIVE_MAINTENANCE_AUTH_TOKEN:-}",
  MAN_SUPPLY_CHAIN_ASSISTANT_AUTH_TOKEN: "${MAN_SUPPLY_CHAIN_ASSISTANT_AUTH_TOKEN:-}",
  RAVEN_AGENT_ENDPOINT: "${RAVEN_AGENT_ENDPOINT:-https://SFCOGSOPS-SNOWHOUSE_AWS_US_WEST_2.snowflakecomputing.com/api/v2/databases/SNOWFLAKE_INTELLIGENCE/schemas/AGENTS/agents/RAVEN_SALES_ASSISTANT:run}"
};
EOF

echo "Environment configuration generated:"
cat /usr/share/nginx/html/env-config.js

# Execute the main container command
exec "$@"

